import React, { useState, useEffect } from 'react';
import {
  FileText,
  Download,
  Printer,
  Share2,
  Sparkles,
  TrendingUp,
  AlertTriangle,
  CheckCircle2,
  Calendar,
  Database,
  ShieldCheck,
  BookOpen,
  Award,
  Layers,
  ArrowUpRight,
  ArrowDownRight,
} from 'lucide-react';
import { MarketOverviewKPIs, TickerData, UserPerformanceReport } from '../types/index.js';
import { getCurrencyMultiplier } from '../utils/currency.js';
import { api } from '../services/api.js';
import { CryptoIcon } from '../components/CryptoIcon.js';

interface ReportsPageProps {
  kpis: MarketOverviewKPIs | null;
  coins: TickerData[];
  currency: 'THB' | 'USDT';
}

export const ReportsPage: React.FC<ReportsPageProps> = ({ kpis, coins, currency }) => {
  const [selectedReportType, setSelectedReportType] = useState<'daily' | 'weekly' | 'risk' | 'personal'>('daily');
  const [isCopied, setIsCopied] = useState(false);
  const [personalReport, setPersonalReport] = useState<UserPerformanceReport | null>(null);
  const [loadingPersonal, setLoadingPersonal] = useState(false);

  const activeUsername = localStorage.getItem('cryptopro_active_username') || 'totokung';
  const activeRole = localStorage.getItem('cryptopro_auth_role') || 'free';

  const now = new Date();
  const reportDate = now.toLocaleDateString('th-TH', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
  const reportTime =
    now.toLocaleTimeString('th-TH', {
      hour: '2-digit',
      minute: '2-digit',
    }) + ' (UTC+7)';

  const topGainers = [...coins].sort((a, b) => b.change24h - a.change24h).slice(0, 3);
  const topAI = [...coins].sort((a, b) => b.aiScore - a.aiScore).slice(0, 3);
  const lowestRiskCoins = [...coins].filter((c) => c.riskLevel === 'Low').slice(0, 3);

  const multiplier = getCurrencyMultiplier(currency);
  const prefix = currency === 'THB' ? '฿' : '$';

  // Load personal report when personal tab selected
  useEffect(() => {
    if (selectedReportType === 'personal' && !personalReport) {
      setLoadingPersonal(true);
      api
        .getUserPerformanceReport()
        .then((data) => setPersonalReport(data))
        .catch((err) => console.error('Failed to load personal performance report:', err))
        .finally(() => setLoadingPersonal(false));
    }
  }, [selectedReportType, personalReport]);

  const reportTypeLabels = {
    daily: {
      title: 'DAILY CRYPTO MARKET BRIEFING',
      subtitle: 'CryptoPro AI Quantitative Daily Momentum & Sentiment Analysis',
      badge: 'Daily Briefing (รายวัน)',
    },
    weekly: {
      title: 'WEEKLY MACRO & SECTOR ROTATION REPORT',
      subtitle: 'CryptoPro AI Macro Trends, Sector Allocation & Flow Insights',
      badge: 'Weekly Macro (รายสัปดาห์)',
    },
    risk: {
      title: 'COMPREHENSIVE RISK & VOLATILITY ASSESSMENT',
      subtitle: 'CryptoPro AI Portfolio Risk Metrics, Stress-Testing & Drawdown Defense',
      badge: 'Risk Assessment (ประเมินความเสี่ยง)',
    },
    personal: {
      title: `PERSONAL TRADING & JOURNAL PERFORMANCE REPORT: ${activeUsername.toUpperCase()}`,
      subtitle: 'สถิติพอร์ต คำสั่งเทรดจำลอง และการสะท้อนผลบทเรียนในฐานข้อมูล Supabase PostgreSQL',
      badge: 'Personal Performance (พอร์ตของฉัน)',
    },
  };

  const currentMeta = reportTypeLabels[selectedReportType];

  const handleCopyReport = () => {
    if (selectedReportType === 'personal' && personalReport) {
      const text =
        `📊 CryptoPro AI Personal Performance Report (${activeUsername})\n\n` +
        `• Win Rate: ${personalReport.winRatePct}%\n` +
        `• Total Trades: ${personalReport.totalTrades} (Closed: ${personalReport.closedTrades})\n` +
        `• Total Realized PnL: ${prefix}${(personalReport.totalRealizedPnl * multiplier).toFixed(2)}\n` +
        `• Profit Factor: ${personalReport.profitFactor}x\n` +
        `• Largest Win: ${prefix}${(personalReport.largestWin * multiplier).toFixed(2)}\n` +
        `• Largest Loss: -${prefix}${(personalReport.largestLoss * multiplier).toFixed(2)}\n` +
        `• Journal Logs: ${personalReport.journalCount} รายการ\n\n` +
        `Generated by CryptoPro AI Platform`;
      navigator.clipboard.writeText(text);
    } else {
      const text =
        `📊 CryptoPro AI Market Intelligence Report [${currentMeta.badge}] (${reportDate})\n\n` +
        `• Total Market Cap: ${kpis?.totalMarketCapFormatted || '-'} (${kpis?.marketCapChange24h || 0}%)\n` +
        `• 24h Volume: ${kpis?.volume24hFormatted || '-'}\n` +
        `• BTC Dominance: ${kpis?.btcDominance || 0}%\n` +
        `• Fear & Greed: ${kpis?.fearAndGreedIndex || 0} (${kpis?.fearAndGreedSentiment || '-'})\n` +
        `• AI Trend: ${kpis?.marketAITrend?.statusTh || '-'}\n\n` +
        `🔥 Top AI Focus:\n` +
        topAI.map((c, i) => `${i + 1}. ${c.symbol} (Score: ${c.aiScore}/100) - ${c.signalLabelTh}`).join('\n') +
        `\n\nGenerated by CryptoPro AI Decision Support Platform`;
      navigator.clipboard.writeText(text);
    }
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleDownloadReport = () => {
    let mdContent = '';

    if (selectedReportType === 'personal' && personalReport) {
      mdContent =
        `# ${currentMeta.title}\n` +
        `**${currentMeta.subtitle}**\n\n` +
        `*ผู้ใช้งาน:* ${activeUsername} (${personalReport.userRole.toUpperCase()})\n` +
        `*วันที่ออกรายงาน:* ${reportDate} ${reportTime}\n\n` +
        `---\n\n` +
        `## 1. สรุปผลการเทรดและสถิติ (Performance Metrics)\n\n` +
        `| ตัวชี้วัด | ค่าที่คำนวณได้ |\n` +
        `|---|---|\n` +
        `| อัตราชนะ (Win Rate) | ${personalReport.winRatePct}% |\n` +
        `| กำไร/ขาดทุนสุทธิ (Net Realized PnL) | ${prefix}${(personalReport.totalRealizedPnl * multiplier).toFixed(2)} |\n` +
        `| Profit Factor | ${personalReport.profitFactor}x |\n` +
        `| จำนวนไม้ที่ปิดแล้ว | ${personalReport.closedTrades} ไม้ (ชนะ ${personalReport.winTrades} / แพ้ ${personalReport.lossTrades}) |\n` +
        `| ไม้ที่ชนะสูงสุด (Largest Win) | ${prefix}${(personalReport.largestWin * multiplier).toFixed(2)} |\n` +
        `| ไม้ที่ขาดทุนสูงสุด (Largest Loss) | -${prefix}${(personalReport.largestLoss * multiplier).toFixed(2)} |\n\n` +
        `## 2. ประสิทธิภาพแยกรายเหรียญ (Performance by Symbol)\n\n` +
        personalReport.performanceBySymbol.map((p) => `- **${p.symbol}:** ${p.tradesCount} ไม้ | กำไรสุทธิ ${prefix}${(p.realizedPnl * multiplier).toFixed(2)} | Win Rate ${p.winRatePct}%`).join('\n') +
        `\n\n## 3. บันทึก Trading Journal ล่าสุด\n\n` +
        personalReport.recentJournals.map((j) => `### ${j.tradeDate} - ${j.title} (${j.marketSentiment})\n${j.dailySummaryTh}\n*บทเรียน:* ${j.lessonsLearned}\n`).join('\n') +
        `\n---\n*จัดทำโดย: CryptoPro AI Cloud Platform*\n`;
    } else {
      const focusList = selectedReportType === 'risk' && lowestRiskCoins.length > 0 ? lowestRiskCoins : topAI;
      mdContent =
        `# ${currentMeta.title}\n` +
        `**${currentMeta.subtitle}**\n\n` +
        `*วันที่รายงาน:* ${reportDate} ${reportTime}\n` +
        `*ประเภท:* ${currentMeta.badge}\n\n` +
        `---\n\n` +
        `## 1. สรุปภาพรวมและสภาวะตลาด (Executive Summary)\n\n` +
        `ตลาดคริปโตเคอร์เรนซีอยู่ในสภาวะ **${kpis?.marketAITrend?.statusTh || 'สอดส่องและติดตาม'}** โดยมีมูลค่าตลาดรวมอยู่ที่ **${kpis?.totalMarketCapFormatted || '-'}** (ปรับตัว ${Number(kpis?.marketCapChange24h) >= 0 ? '+' : ''}${kpis?.marketCapChange24h || 0}%) ปริมาณการซื้อขาย 24 ชั่วโมง **${kpis?.volume24hFormatted || '-'}** ดัชนีความกลัวและความโลภ (Fear & Greed Index) อยู่ที่ระดับ **${kpis?.fearAndGreedIndex || 0} (${kpis?.fearAndGreedSentiment || '-'})**\n\n` +
        `## 2. ดัชนีชี้วัดมหภาค (Macro Metrics)\n\n` +
        `| ตัวชี้วัด (Metric) | มูลค่า / ระดับ | หมายเหตุ |\n` +
        `|---|---|---|\n` +
        `| BTC Dominance | ${kpis?.btcDominance || 0}% | สัดส่วนการครองตลาด |\n` +
        `| Bitcoin Price | ${prefix}${kpis ? (kpis.btcPrice * multiplier).toLocaleString(undefined, { maximumFractionDigits: 0 }) : '-'} | 24h Change: ${Number(kpis?.btcChange24h) >= 0 ? '+' : ''}${kpis?.btcChange24h}% |\n` +
        `| Ethereum Price | ${prefix}${kpis ? (kpis.ethPrice * multiplier).toLocaleString(undefined, { maximumFractionDigits: 0 }) : '-'} | 24h Change: ${Number(kpis?.ethChange24h) >= 0 ? '+' : ''}${kpis?.ethChange24h}% |\n` +
        `| Fear & Greed | ${kpis?.fearAndGreedIndex || 50} | ${kpis?.fearAndGreedSentiment || 'Neutral'} |\n\n` +
        `## 3. โอกาสการลงทุนที่โดดเด่นประจำรายงาน (Top AI Focus Opportunities)\n\n` +
        focusList
          .map(
            (c, i) =>
              `### ${i + 1}. ${c.symbol} (${c.name})\n` +
              `- **AI Score:** ${c.aiScore}/100 | **Technical Score:** ${c.technicalScore}/100\n` +
              `- **สัญญาณ:** ${c.signalLabelTh || c.signal}\n` +
              `- **ระดับความเสี่ยง:** ${c.riskLevel || 'Medium'}\n` +
              `- **บทวิเคราะห์ AI:** ${c.signalReasonTh || '-'}\n`
          )
          .join('\n') +
        `\n## 4. แนวทางการบริหารความเสี่ยงและการยกเลิกแผน (Risk Management & Invalidation Rules)\n\n` +
        `- กำหนด Stop Loss ไม่เกิน 2-3% ของพอร์ตโฟลิโอต่อคำสั่งซื้อขาย\n` +
        `- หากราคาหลุดแนวรับสำคัญ หรือโครงสร้างตลาดเปลี่ยนเป็น Lower Low ให้ยกเลิกแผนทันที\n` +
        `- กระจายความเสี่ยงในสินทรัพย์หมวดหมู่หลัก (Core Assets) ควบคู่กับกลุ่ม High Growth\n\n` +
        `---\n` +
        `*จัดทำโดย: CryptoPro AI Decision Support Platform*\n`;
    }

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `CryptoPro_Report_${selectedReportType}_${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', maxWidth: '1000px' }}>
      {/* Header & Report Actions */}
      <div className="card-header-row" style={{ marginBottom: '0', flexWrap: 'wrap', gap: '12px' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' }}>
            <FileText size={22} color="var(--neon-cyan)" />
            <h2 style={{ fontSize: '20px', fontWeight: 800 }}>
              รายงาน &amp; สถิติเชิงปริมาณ (Intelligence &amp; Performance Reports)
            </h2>
            <span
              style={{
                fontSize: '11px',
                fontWeight: 700,
                color: '#10B981',
                backgroundColor: 'rgba(16, 185, 129, 0.12)',
                border: '1px solid rgba(16, 185, 129, 0.35)',
                borderRadius: '6px',
                padding: '3px 8px',
                display: 'inline-flex',
                alignItems: 'center',
                gap: '5px',
              }}
            >
              <Database size={12} />
              <span>Supabase DB Synced</span>
            </span>
            <span
              style={{
                fontSize: '11px',
                fontWeight: 700,
                color: '#38BDF8',
                backgroundColor: 'rgba(56, 189, 248, 0.1)',
                border: '1px solid rgba(56, 189, 248, 0.25)',
                borderRadius: '6px',
                padding: '3px 8px',
                display: 'inline-flex',
                alignItems: 'center',
                gap: '5px',
              }}
            >
              <ShieldCheck size={12} />
              <span>ผู้ใช้: {activeUsername} ({activeRole.toUpperCase()})</span>
            </span>
          </div>
          <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginTop: '4px' }}>
            สรุปภาพรวมตลาด โอกาสการลงทุน และรายงานสถิติพอร์ตส่วนบุคคลจากฐานข้อมูลจริง
          </p>
        </div>

        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
          <button onClick={handleDownloadReport} className="btn-secondary" style={{ fontSize: '12px', gap: '6px' }}>
            <Download size={14} color="var(--neon-green)" />
            <span>ดาวน์โหลด (.md)</span>
          </button>
          <button onClick={handleCopyReport} className="btn-secondary" style={{ fontSize: '12px', gap: '6px' }}>
            <Share2 size={14} />
            <span>{isCopied ? 'คัดลอกแล้ว!' : 'แชร์ / คัดลอก'}</span>
          </button>
          <button onClick={() => window.print()} className="btn-primary" style={{ fontSize: '12px', gap: '6px' }}>
            <Printer size={14} />
            <span>พิมพ์ / PDF</span>
          </button>
        </div>
      </div>

      {/* Report Type Selector */}
      <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
        {[
          { id: 'daily', label: 'รายงานประจำวัน (Daily Briefing)' },
          { id: 'weekly', label: 'รายงานแนวโน้มรายสัปดาห์ (Weekly Macro)' },
          { id: 'risk', label: 'รายงานประเมินความเสี่ยง (Risk Assessment)' },
          { id: 'personal', label: '⭐ สถิติพอร์ตและการเทรดของฉัน (My Trading & Journals)' },
        ].map((type) => (
          <button
            key={type.id}
            onClick={() => setSelectedReportType(type.id as any)}
            style={{
              background: selectedReportType === type.id ? 'var(--neon-blue)' : 'var(--bg-card)',
              border: selectedReportType === type.id ? '1px solid #3B82F6' : '1px solid var(--border-color)',
              color: selectedReportType === type.id ? '#FFF' : 'var(--text-secondary)',
              padding: '6px 14px',
              borderRadius: '8px',
              fontSize: '12px',
              fontWeight: 600,
              cursor: 'pointer',
              transition: 'all 0.15s ease',
            }}
          >
            {type.label}
          </button>
        ))}
      </div>

      {/* ======================================================== */}
      {/* PERSONAL PERFORMANCE REPORT VIEW                          */}
      {/* ======================================================== */}
      {selectedReportType === 'personal' ? (
        <div
          className="crypto-card report-paper-card"
          style={{
            padding: '24px',
            backgroundColor: 'var(--bg-card)',
            border: '1px solid var(--border-color)',
            display: 'flex',
            flexDirection: 'column',
            gap: '20px',
          }}
        >
          {loadingPersonal ? (
            <div style={{ textAlign: 'center', padding: '40px', color: 'var(--text-muted)' }}>
              กำลังประมวลผลสถิติจากฐานข้อมูล Supabase PostgreSQL...
            </div>
          ) : personalReport ? (
            <>
              {/* Report Header */}
              <div style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '16px' }}>
                <div style={{ fontSize: '18px', fontWeight: 900, color: 'var(--text-primary)' }}>
                  {currentMeta.title}
                </div>
                <div style={{ fontSize: '12px', color: 'var(--neon-cyan)', fontWeight: 700, marginTop: '2px' }}>
                  {currentMeta.subtitle}
                </div>
                <div style={{ fontSize: '11.5px', color: 'var(--text-muted)', marginTop: '4px' }}>
                  📅 วันที่ออกรายงาน: {reportDate} • {reportTime}
                </div>
              </div>

              {/* 4 KPI Cards */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '12px' }}>
                <div style={{ padding: '14px', borderRadius: '10px', backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid var(--border-color)' }}>
                  <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>อัตราชนะ (Win Rate)</div>
                  <div style={{ fontSize: '24px', fontWeight: 900, color: 'var(--neon-cyan)', marginTop: '4px' }}>
                    {personalReport.winRatePct}%
                  </div>
                  <div style={{ fontSize: '10.5px', color: 'var(--text-muted)' }}>
                    ชนะ {personalReport.winTrades} จาก {personalReport.closedTrades} ออเดอร์
                  </div>
                </div>

                <div style={{ padding: '14px', borderRadius: '10px', backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid var(--border-color)' }}>
                  <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>กำไรสุทธิสะสม (Net Realized PnL)</div>
                  <div style={{ fontSize: '24px', fontWeight: 900, color: personalReport.totalRealizedPnl >= 0 ? 'var(--neon-green-light)' : 'var(--neon-red)', marginTop: '4px' }}>
                    {personalReport.totalRealizedPnl >= 0 ? '+' : ''}{prefix}{(personalReport.totalRealizedPnl * multiplier).toFixed(2)}
                  </div>
                  <div style={{ fontSize: '10.5px', color: 'var(--text-muted)' }}>
                    บันทึกจากคำสั่งปิดใน PostgreSQL
                  </div>
                </div>

                <div style={{ padding: '14px', borderRadius: '10px', backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid var(--border-color)' }}>
                  <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Profit Factor</div>
                  <div style={{ fontSize: '24px', fontWeight: 900, color: '#A78BFA', marginTop: '4px' }}>
                    {personalReport.profitFactor}x
                  </div>
                  <div style={{ fontSize: '10.5px', color: 'var(--text-muted)' }}>
                    สัดส่วนกำไรต่อผลขาดทุน
                  </div>
                </div>

                <div style={{ padding: '14px', borderRadius: '10px', backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid var(--border-color)' }}>
                  <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>บันทึก Trading Journal</div>
                  <div style={{ fontSize: '24px', fontWeight: 900, color: '#38BDF8', marginTop: '4px' }}>
                    {personalReport.journalCount} บันทึก
                  </div>
                  <div style={{ fontSize: '10.5px', color: 'var(--text-muted)' }}>
                    จัดเก็บในตาราง <code>public.trading_journals</code>
                  </div>
                </div>
              </div>

              {/* Performance by Symbol */}
              <div>
                <h4 style={{ fontSize: '14px', fontWeight: 800, color: '#FFF', marginBottom: '10px' }}>
                  📊 สถิติผลการเทรดแยกตามเหรียญ (Performance by Symbol)
                </h4>
                {personalReport.performanceBySymbol.length === 0 ? (
                  <div style={{ padding: '16px', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '8px', color: 'var(--text-muted)', fontSize: '12px' }}>
                    ยังไม่มีออเดอร์ที่ปิดในระบบ
                  </div>
                ) : (
                  <div style={{ overflowX: 'auto' }}>
                    <table className="crypto-table" style={{ fontSize: '12px' }}>
                      <thead>
                        <tr>
                          <th>เหรียญ</th>
                          <th style={{ textAlign: 'right' }}>จำนวนไม้</th>
                          <th style={{ textAlign: 'right' }}>กำไรสุทธิ</th>
                          <th style={{ textAlign: 'right' }}>Win Rate %</th>
                        </tr>
                      </thead>
                      <tbody>
                        {personalReport.performanceBySymbol.map((s) => (
                          <tr key={s.symbol}>
                            <td style={{ fontWeight: 800 }}>{s.symbol}</td>
                            <td style={{ textAlign: 'right' }}>{s.tradesCount}</td>
                            <td style={{ textAlign: 'right', fontWeight: 700, color: s.realizedPnl >= 0 ? 'var(--neon-green-light)' : 'var(--neon-red)' }}>
                              {s.realizedPnl >= 0 ? '+' : ''}{prefix}{(s.realizedPnl * multiplier).toFixed(2)}
                            </td>
                            <td style={{ textAlign: 'right', fontWeight: 700, color: 'var(--neon-cyan)' }}>
                              {s.winRatePct}%
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>

              {/* Recent Journal Insights */}
              <div>
                <h4 style={{ fontSize: '14px', fontWeight: 800, color: '#FFF', marginBottom: '10px' }}>
                  📝 บทเรียนและข้อคิดจาก Trading Journal ล่าสุด
                </h4>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                  {personalReport.recentJournals.length === 0 ? (
                    <div style={{ padding: '16px', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '8px', color: 'var(--text-muted)', fontSize: '12px' }}>
                      ยังไม่มีบันทึก Trading Journal
                    </div>
                  ) : (
                    personalReport.recentJournals.map((j) => (
                      <div
                        key={j.id}
                        style={{
                          padding: '12px 16px',
                          borderRadius: '8px',
                          backgroundColor: 'rgba(255, 255, 255, 0.02)',
                          border: '1px solid rgba(255, 255, 255, 0.06)',
                          display: 'flex',
                          flexDirection: 'column',
                          gap: '6px',
                        }}
                      >
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                          <strong style={{ color: '#FFF', fontSize: '13px' }}>{j.title}</strong>
                          <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>{j.tradeDate}</span>
                        </div>
                        <div style={{ fontSize: '12px', color: '#CBD5E1' }}>{j.dailySummaryTh}</div>
                        {j.lessonsLearned && (
                          <div style={{ fontSize: '11.5px', color: '#FDE68A' }}>
                            💡 {j.lessonsLearned}
                          </div>
                        )}
                      </div>
                    ))
                  )}
                </div>
              </div>
            </>
          ) : null}
        </div>
      ) : (
        /* Market Intelligence Report View (Default) */
        <div
          className="crypto-card report-paper-card"
          style={{
            padding: '24px',
            backgroundColor: 'var(--bg-card)',
            border: '1px solid var(--border-color)',
            display: 'flex',
            flexDirection: 'column',
            gap: '20px',
          }}
        >
          {/* Report Top Meta */}
          <div className="report-top-meta" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border-color)', paddingBottom: '16px', flexWrap: 'wrap', gap: '10px' }}>
            <div>
              <div style={{ fontSize: '18px', fontWeight: 900, color: 'var(--text-primary)', letterSpacing: '0.3px' }}>
                {currentMeta.title}
              </div>
              <div style={{ fontSize: '12px', color: 'var(--neon-cyan)', fontWeight: 700, marginTop: '2px' }}>
                {currentMeta.subtitle}
              </div>
            </div>

            <div style={{ textAlign: 'right', fontSize: '11.5px', color: 'var(--text-muted)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '4px', justifyContent: 'flex-end' }}>
                <Calendar size={13} />
                <span>{reportDate} • {reportTime}</span>
              </div>
              <div style={{ color: 'var(--neon-green)', marginTop: '2px', fontWeight: 600 }}>
                ● Live Multi-Exchange Sync ({currentMeta.badge})
              </div>
            </div>
          </div>

          {/* Section 1: Executive Summary */}
          <div>
            <div style={{ fontSize: '14px', fontWeight: 800, color: 'var(--text-primary)', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Sparkles size={16} color="var(--neon-green)" />
              1. สรุปภาพรวมและสภาวะตลาด (Executive Summary)
            </div>
            <div style={{ fontSize: '12.5px', lineHeight: 1.6, color: 'var(--text-secondary)', padding: '12px 14px', backgroundColor: 'rgba(255, 255, 255, 0.02)', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
              สภาวะตลาดโดยรวมในปัจจุบันถูกประเมินโดย AI Engine อยู่ในระดับ <strong>{kpis?.marketAITrend?.statusTh || 'สอดส่องและติดตาม'}</strong> มูลค่าตลาดรวมอยู่ที่ <strong>{kpis?.totalMarketCapFormatted || '-'}</strong> ({Number(kpis?.marketCapChange24h) >= 0 ? '+' : ''}{kpis?.marketCapChange24h || 0}% ใน 24 ชั่วโมงที่ผ่านมา) ปริมาณการซื้อขายรวม 24 ชั่วโมง <strong>{kpis?.volume24hFormatted || '-'}</strong> สัดส่วนการครองตลาดของ Bitcoin (BTC Dominance) อยู่ที่ <strong>{kpis?.btcDominance || 0}%</strong> และดัชนีชี้วัดอารมณ์ตลาด Fear &amp; Greed Index อยู่ที่ระดับ <strong>{kpis?.fearAndGreedIndex || 0} ({kpis?.fearAndGreedSentiment || '-'})</strong>
            </div>
          </div>

          {/* Section 2: Macro Metrics */}
          <div>
            <div style={{ fontSize: '14px', fontWeight: 800, color: 'var(--text-primary)', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <TrendingUp size={16} color="var(--neon-blue)" />
              2. ดัชนีชี้วัดมหภาค (Macro Metrics)
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '10px' }}>
              <div style={{ padding: '10px', borderRadius: '8px', backgroundColor: 'rgba(255, 255, 255, 0.02)', border: '1px solid var(--border-color)' }}>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>BTC Dominance</div>
                <div style={{ fontSize: '18px', fontWeight: 800, marginTop: '2px' }}>{kpis?.btcDominance || 0}%</div>
                <div style={{ fontSize: '10.5px', color: 'var(--text-muted)' }}>สัดส่วนการครองตลาด</div>
              </div>
              <div style={{ padding: '10px', borderRadius: '8px', backgroundColor: 'rgba(255, 255, 255, 0.02)', border: '1px solid var(--border-color)' }}>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Bitcoin (BTC)</div>
                <div style={{ fontSize: '18px', fontWeight: 800, marginTop: '2px' }}>
                  {prefix}{kpis ? (kpis.btcPrice * multiplier).toLocaleString(undefined, { maximumFractionDigits: 0 }) : '-'}
                </div>
                <div style={{ fontSize: '10.5px', color: Number(kpis?.btcChange24h) >= 0 ? 'var(--neon-green-light)' : 'var(--neon-red)' }}>
                  {Number(kpis?.btcChange24h) >= 0 ? '+' : ''}{kpis?.btcChange24h}%
                </div>
              </div>
              <div style={{ padding: '10px', borderRadius: '8px', backgroundColor: 'rgba(255, 255, 255, 0.02)', border: '1px solid var(--border-color)' }}>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Ethereum (ETH)</div>
                <div style={{ fontSize: '18px', fontWeight: 800, marginTop: '2px' }}>
                  {prefix}{kpis ? (kpis.ethPrice * multiplier).toLocaleString(undefined, { maximumFractionDigits: 0 }) : '-'}
                </div>
                <div style={{ fontSize: '10.5px', color: Number(kpis?.ethChange24h) >= 0 ? 'var(--neon-green-light)' : 'var(--neon-red)' }}>
                  {Number(kpis?.ethChange24h) >= 0 ? '+' : ''}{kpis?.ethChange24h}%
                </div>
              </div>
              <div style={{ padding: '10px', borderRadius: '8px', backgroundColor: 'rgba(255, 255, 255, 0.02)', border: '1px solid var(--border-color)' }}>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Fear &amp; Greed</div>
                <div style={{ fontSize: '18px', fontWeight: 800, marginTop: '2px', color: 'var(--neon-cyan)' }}>
                  {kpis?.fearAndGreedIndex || 0}
                </div>
                <div style={{ fontSize: '10.5px', color: 'var(--text-muted)' }}>{kpis?.fearAndGreedSentiment || '-'}</div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
