import React, { useState } from 'react';
import { FileText, Download, Printer, Share2, Sparkles, TrendingUp, AlertTriangle, CheckCircle2, Calendar } from 'lucide-react';
import { MarketOverviewKPIs, TickerData } from '../types/index.js';

interface ReportsPageProps {
  kpis: MarketOverviewKPIs | null;
  coins: TickerData[];
  currency: 'THB' | 'USDT';
}

export const ReportsPage: React.FC<ReportsPageProps> = ({ kpis, coins, currency }) => {
  const [reportDate] = useState('19 กันยายน 2026');
  const [reportTime] = useState('17:00 (UTC+7)');
  const [selectedReportType, setSelectedReportType] = useState<'daily' | 'weekly' | 'risk'>('daily');
  const [isCopied, setIsCopied] = useState(false);

  const topGainers = [...coins].sort((a, b) => b.change24h - a.change24h).slice(0, 3);
  const topAI = [...coins].sort((a, b) => b.aiScore - a.aiScore).slice(0, 3);

  const multiplier = currency === 'THB' ? 34.5 : 1;
  const prefix = currency === 'THB' ? '฿' : '$';

  const handleCopyReport = () => {
    const text = `📊 CryptoPro AI Market Intelligence Report (${reportDate})\n\n` +
      `• Total Market Cap: ${kpis?.totalMarketCapFormatted} (${kpis?.marketCapChange24h}%\n` +
      `• 24h Volume: ${kpis?.volume24hFormatted}\n` +
      `• BTC Dominance: ${kpis?.btcDominance}%\n` +
      `• Fear & Greed: ${kpis?.fearAndGreedIndex} (${kpis?.fearAndGreedSentiment})\n` +
      `• AI Trend: ${kpis?.marketAITrend.statusTh}\n\n` +
      `🔥 Top AI Opportunities:\n` +
      topAI.map((c, i) => `${i + 1}. ${c.symbol} (Score: ${c.aiScore}/100) - ${c.signalLabelTh}`).join('\n') +
      `\n\nGenerated by CryptoPro AI Decision Support Platform`;

    navigator.clipboard.writeText(text);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', maxWidth: '1000px' }}>
      {/* Header & Report Actions */}
      <div className="card-header-row" style={{ marginBottom: '0' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <FileText size={22} color="var(--neon-cyan)" />
            <h2 style={{ fontSize: '20px', fontWeight: 800 }}>
              รายงานวิเคราะห์สภาวะตลาด (Market Intelligence Report)
            </h2>
          </div>
          <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginTop: '4px' }}>
            สรุปภาพรวมตลาดคริปโต โอกาสการลงทุนรายวัน และการประเมินความเสี่ยงเชิงปริมาณ
          </p>
        </div>

        <div style={{ display: 'flex', gap: '8px' }}>
          <button onClick={handleCopyReport} className="btn-secondary" style={{ fontSize: '12px' }}>
            <Share2 size={14} />
            <span>{isCopied ? 'คัดลอกแล้ว!' : 'แชร์ / คัดลอก'}</span>
          </button>
          <button onClick={() => window.print()} className="btn-primary" style={{ fontSize: '12px' }}>
            <Printer size={14} />
            <span>พิมพ์ / บันทึก PDF</span>
          </button>
        </div>
      </div>

      {/* Report Type Selector */}
      <div style={{ display: 'flex', gap: '8px' }}>
        {[
          { id: 'daily', label: 'รายงานประจำวัน (Daily Briefing)' },
          { id: 'weekly', label: 'รายงานแนวโน้มรายสัปดาห์ (Weekly Macro)' },
          { id: 'risk', label: 'รายงานประเมินความเสี่ยง (Risk Assessment)' },
        ].map((type) => (
          <button
            key={type.id}
            onClick={() => setSelectedReportType(type.id as any)}
            style={{
              background: selectedReportType === type.id ? 'var(--neon-blue)' : 'var(--bg-card)',
              border: selectedReportType === type.id ? '1px solid #3B82F6' : '1px solid var(--border-color)',
              color: selectedReportType === type.id ? '#FFF' : 'var(--text-secondary)',
              padding: '6px 14px',
              borderRadius: '8px',
              fontSize: '12px',
              fontWeight: 600,
              cursor: 'pointer',
            }}
          >
            {type.label}
          </button>
        ))}
      </div>

      {/* Report Paper Container */}
      <div
        className="crypto-card"
        style={{
          padding: '28px',
          backgroundColor: '#0F172A',
          border: '1px solid rgba(59, 130, 246, 0.25)',
          display: 'flex',
          flexDirection: 'column',
          gap: '20px',
        }}
      >
        {/* Report Top Meta */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid rgba(255, 255, 255, 0.06)', paddingBottom: '16px' }}>
          <div>
            <div style={{ fontSize: '18px', fontWeight: 900, color: '#FFF' }}>
              CRYPTO INVESTMENT INTELLIGENCE REPORT
            </div>
            <div style={{ fontSize: '12px', color: 'var(--neon-cyan)', fontWeight: 700, marginTop: '2px' }}>
              CryptoPro AI Quantitative &amp; Sentiment Analysis
            </div>
          </div>

          <div style={{ textAlign: 'right', fontSize: '11.5px', color: 'var(--text-muted)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '4px', justifyContent: 'flex-end' }}>
              <Calendar size={13} />
              <span>{reportDate} • {reportTime}</span>
            </div>
            <div style={{ color: 'var(--neon-green)', marginTop: '2px', fontWeight: 600 }}>
              ● Live Multi-Exchange Sync
            </div>
          </div>
        </div>

        {/* Section 1: Executive Market Summary */}
        <div>
          <h3 style={{ fontSize: '15px', fontWeight: 800, color: '#F1F5F9', marginBottom: '10px', display: 'flex', alignItems: 'center', gap: '6px' }}>
            <TrendingUp size={16} color="var(--neon-green)" />
            1. สรุปภาพรวมและสภาวะตลาด (Executive Summary)
          </h3>
          <p style={{ fontSize: '13px', lineHeight: 1.6, color: '#CBD5E1' }}>
            ตลาดคริปโตเคอร์เรนซีในรอบ 24 ชั่วโมงที่ผ่านมาอยู่ในสภาวะ <strong>{kpis?.marketAITrend.statusTh}</strong> โดยมีมูลค่าตลาดรวมอยู่ที่ <strong>{kpis?.totalMarketCapFormatted}</strong> (ปรับตัวขึ้น +{kpis?.marketCapChange24h}%) พร้อมปริมาณการซื้อขายรวม <strong>{kpis?.volume24hFormatted}</strong> ดัชนีความกลัวและความโลภ (Fear &amp; Greed Index) ปิดที่ระดับ <strong>{kpis?.fearAndGreedIndex} ({kpis?.fearAndGreedSentiment})</strong> สะท้อนถึงความเชื่อมั่นของนักลงทุนที่เริ่มกลับมาไหลเข้าสะสมสินทรัพย์เสี่ยง โดยเฉพาะในกลุ่ม <strong>Layer 1/Layer 2, DeFi และ AI/DePIN</strong>
          </p>
        </div>

        {/* Section 2: Macro Metrics Grid */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '10px' }}>
          <div style={{ backgroundColor: 'rgba(255, 255, 255, 0.03)', padding: '10px', borderRadius: '8px' }}>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>BTC Dominance</div>
            <div style={{ fontSize: '16px', fontWeight: 800, marginTop: '2px' }}>{kpis?.btcDominance}%</div>
            <div style={{ fontSize: '10.5px', color: 'var(--text-secondary)' }}>สัดส่วนการครองตลาด</div>
          </div>

          <div style={{ backgroundColor: 'rgba(255, 255, 255, 0.03)', padding: '10px', borderRadius: '8px' }}>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Bitcoin Price</div>
            <div style={{ fontSize: '16px', fontWeight: 800, marginTop: '2px' }}>
              {prefix}{kpis ? (kpis.btcPrice * multiplier).toLocaleString(undefined, { maximumFractionDigits: 0 }) : '-'}
            </div>
            <div style={{ fontSize: '10.5px', color: 'var(--neon-green-light)' }}>+{kpis?.btcChange24h}% (24h)</div>
          </div>

          <div style={{ backgroundColor: 'rgba(255, 255, 255, 0.03)', padding: '10px', borderRadius: '8px' }}>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Ethereum Price</div>
            <div style={{ fontSize: '16px', fontWeight: 800, marginTop: '2px' }}>
              {prefix}{kpis ? (kpis.ethPrice * multiplier).toLocaleString(undefined, { maximumFractionDigits: 0 }) : '-'}
            </div>
            <div style={{ fontSize: '10.5px', color: 'var(--neon-green-light)' }}>+{kpis?.ethChange24h}% (24h)</div>
          </div>

          <div style={{ backgroundColor: 'rgba(255, 255, 255, 0.03)', padding: '10px', borderRadius: '8px' }}>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>ตลาด Bullish</div>
            <div style={{ fontSize: '16px', fontWeight: 800, color: 'var(--neon-green-light)', marginTop: '2px' }}>
              31 / 38 เหรียญ
            </div>
            <div style={{ fontSize: '10.5px', color: 'var(--text-secondary)' }}>อัตราความแข็งแกร่ง 81.5%</div>
          </div>
        </div>

        {/* Section 3: Top Opportunities (AI Focus) */}
        <div>
          <h3 style={{ fontSize: '15px', fontWeight: 800, color: '#F1F5F9', marginBottom: '10px', display: 'flex', alignItems: 'center', gap: '6px' }}>
            <Sparkles size={16} color="var(--neon-cyan)" />
            2. โอกาสการลงทุนที่โดดเด่นประจำวัน (Top AI Opportunities)
          </h3>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px' }}>
            {topAI.map((coin, idx) => (
              <div
                key={coin.symbol}
                style={{
                  backgroundColor: 'rgba(255, 255, 255, 0.02)',
                  border: '1px solid rgba(59, 130, 246, 0.25)',
                  borderRadius: '10px',
                  padding: '12px',
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '6px' }}>
                  <span style={{ fontWeight: 800, fontSize: '15px' }}>{idx + 1}. {coin.symbol}</span>
                  <span className="badge badge-strong-buy">{coin.signalLabelTh}</span>
                </div>
                <div style={{ fontSize: '13px', fontWeight: 700, color: 'var(--neon-cyan)', marginBottom: '6px' }}>
                  AI Score: {coin.aiScore}/100 • Tech: {coin.technicalScore}
                </div>
                <p style={{ fontSize: '11.5px', color: 'var(--text-secondary)', lineHeight: 1.4 }}>
                  {coin.signalReasonTh}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Section 4: Risk & Invalidation Guidance */}
        <div style={{ backgroundColor: 'rgba(239, 68, 68, 0.06)', border: '1px solid rgba(239, 68, 68, 0.2)', borderRadius: '10px', padding: '14px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '13.5px', fontWeight: 800, color: '#EF4444', marginBottom: '6px' }}>
            <AlertTriangle size={16} />
            3. แนวทางการบริหารความเสี่ยงและการยกเลิกแผน (Risk &amp; Invalidation Rules)
          </div>
          <ul style={{ paddingLeft: '20px', fontSize: '12px', color: '#E2E8F0', lineHeight: 1.6 }}>
            <li><strong>Position Sizing:</strong> ควบคุมความเสี่ยงไม่เกิน 1.5% - 2.0% ของพอร์ตรวมต่อหนึ่งไม้การลงทุน</li>
            <li><strong>Invalidation Trigger:</strong> หาก Bitcoin ปิดแท่ง 4H หลุดต่ำกว่าเส้น EMA 200 หรือเกิด Fake Breakout ให้ชะลอการเปิด Position ใหม่ในกลุ่ม Altcoins</li>
            <li><strong>Profit Taking:</strong> แบ่งไม้ขายทำกำไร (Partial TP) ที่อัตราส่วน Risk/Reward 1:2 และเลื่อนจุดตัดขาดทุนขึ้นมาที่หน้าทุน (Trailing Stop)</li>
          </ul>
        </div>

        {/* Footer Disclaimer */}
        <div style={{ borderTop: '1px solid rgba(255, 255, 255, 0.06)', paddingTop: '12px', fontSize: '11px', color: 'var(--text-muted)', textAlign: 'center' }}>
          เอกสารนี้จัดทำโดย CryptoPro AI Decision Support System เพื่อเป็นข้อมูลประกอบการตัดสินใจลงทุน ไม่ใช่คำชี้ชวนการลงทุน การลงทุนใน Cryptocurrency มีความเสี่ยงสูง ผู้ลงทุนควรศึกษาข้อมูลและบริหารความเสี่ยงอย่างรอบคอบ
        </div>
      </div>
    </div>
  );
};
