import React, { useState } from 'react';
import { FileText, Download, Printer, Share2, Sparkles, TrendingUp, AlertTriangle, CheckCircle2, Calendar } from 'lucide-react';
import { MarketOverviewKPIs, TickerData } from '../types/index.js';
import { getCurrencyMultiplier } from '../utils/currency.js';

interface ReportsPageProps {
  kpis: MarketOverviewKPIs | null;
  coins: TickerData[];
  currency: 'THB' | 'USDT';
}

export const ReportsPage: React.FC<ReportsPageProps> = ({ kpis, coins, currency }) => {
  const [selectedReportType, setSelectedReportType] = useState<'daily' | 'weekly' | 'risk'>('daily');
  const [isCopied, setIsCopied] = useState(false);

  const now = new Date();
  const reportDate = now.toLocaleDateString('th-TH', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
  const reportTime = now.toLocaleTimeString('th-TH', {
    hour: '2-digit',
    minute: '2-digit',
  }) + ' (UTC+7)';

  const topGainers = [...coins].sort((a, b) => b.change24h - a.change24h).slice(0, 3);
  const topAI = [...coins].sort((a, b) => b.aiScore - a.aiScore).slice(0, 3);
  const lowestRiskCoins = [...coins].filter(c => c.riskLevel === 'Low').slice(0, 3);

  const multiplier = getCurrencyMultiplier(currency);
  const prefix = currency === 'THB' ? '฿' : '$';

  const reportTypeLabels = {
    daily: {
      title: 'DAILY CRYPTO MARKET BRIEFING',
      subtitle: 'CryptoPro AI Quantitative Daily Momentum & Sentiment Analysis',
      badge: 'Daily Briefing (รายวัน)',
    },
    weekly: {
      title: 'WEEKLY MACRO & SECTOR ROTATION REPORT',
      subtitle: 'CryptoPro AI Macro Trends, Sector Allocation & Flow Insights',
      badge: 'Weekly Macro (รายสัปดาห์)',
    },
    risk: {
      title: 'COMPREHENSIVE RISK & VOLATILITY ASSESSMENT',
      subtitle: 'CryptoPro AI Portfolio Risk Metrics, Stress-Testing & Drawdown Defense',
      badge: 'Risk Assessment (ประเมินความเสี่ยง)',
    },
  };

  const currentMeta = reportTypeLabels[selectedReportType];

  const handleCopyReport = () => {
    const text = `📊 CryptoPro AI Market Intelligence Report [${currentMeta.badge}] (${reportDate})\n\n` +
      `• Total Market Cap: ${kpis?.totalMarketCapFormatted || '-'} (${kpis?.marketCapChange24h || 0}%)\n` +
      `• 24h Volume: ${kpis?.volume24hFormatted || '-'}\n` +
      `• BTC Dominance: ${kpis?.btcDominance || 0}%\n` +
      `• Fear & Greed: ${kpis?.fearAndGreedIndex || 0} (${kpis?.fearAndGreedSentiment || '-'})\n` +
      `• AI Trend: ${kpis?.marketAITrend?.statusTh || '-'}\n\n` +
      `🔥 Top AI Focus:\n` +
      topAI.map((c, i) => `${i + 1}. ${c.symbol} (Score: ${c.aiScore}/100) - ${c.signalLabelTh}`).join('\n') +
      `\n\nGenerated by CryptoPro AI Decision Support Platform`;

    navigator.clipboard.writeText(text);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleDownloadReport = () => {
    const focusList = (selectedReportType === 'risk' && lowestRiskCoins.length > 0 ? lowestRiskCoins : topAI);
    const mdContent = `# ${currentMeta.title}\n` +
      `**${currentMeta.subtitle}**\n\n` +
      `*วันที่รายงาน:* ${reportDate} ${reportTime}\n` +
      `*ประเภท:* ${currentMeta.badge}\n\n` +
      `---\n\n` +
      `## 1. สรุปภาพรวมและสภาวะตลาด (Executive Summary)\n\n` +
      `ตลาดคริปโตเคอร์เรนซีอยู่ในสภาวะ **${kpis?.marketAITrend?.statusTh || 'สอดส่องและติดตาม'}** โดยมีมูลค่าตลาดรวมอยู่ที่ **${kpis?.totalMarketCapFormatted || '-'}** (ปรับตัว ${Number(kpis?.marketCapChange24h) >= 0 ? '+' : ''}${kpis?.marketCapChange24h || 0}%) ปริมาณการซื้อขาย 24 ชั่วโมง **${kpis?.volume24hFormatted || '-'}** ดัชนีความกลัวและความโลภ (Fear & Greed Index) อยู่ที่ระดับ **${kpis?.fearAndGreedIndex || 0} (${kpis?.fearAndGreedSentiment || '-'})**\n\n` +
      `## 2. ดัชนีชี้วัดมหภาค (Macro Metrics)\n\n` +
      `| ตัวชี้วัด (Metric) | มูลค่า / ระดับ | หมายเหตุ |\n` +
      `|---|---|---|\n` +
      `| BTC Dominance | ${kpis?.btcDominance || 0}% | สัดส่วนการครองตลาด |\n` +
      `| Bitcoin Price | ${prefix}${kpis ? (kpis.btcPrice * multiplier).toLocaleString(undefined, { maximumFractionDigits: 0 }) : '-'} | 24h Change: ${Number(kpis?.btcChange24h) >= 0 ? '+' : ''}${kpis?.btcChange24h}% |\n` +
      `| Ethereum Price | ${prefix}${kpis ? (kpis.ethPrice * multiplier).toLocaleString(undefined, { maximumFractionDigits: 0 }) : '-'} | 24h Change: ${Number(kpis?.ethChange24h) >= 0 ? '+' : ''}${kpis?.ethChange24h}% |\n` +
      `| Fear & Greed | ${kpis?.fearAndGreedIndex || 50} | ${kpis?.fearAndGreedSentiment || 'Neutral'} |\n\n` +
      `## 3. โอกาสการลงทุนที่โดดเด่นประจำรายงาน (Top AI Focus Opportunities)\n\n` +
      focusList.map((c, i) => `### ${i + 1}. ${c.symbol} (${c.name})\n` +
        `- **AI Score:** ${c.aiScore}/100 | **Technical Score:** ${c.technicalScore}/100\n` +
        `- **สัญญาณ:** ${c.signalLabelTh || c.signal}\n` +
        `- **ระดับความเสี่ยง:** ${c.riskLevel || 'Medium'}\n` +
        `- **บทวิเคราะห์ AI:** ${c.signalReasonTh || '-'}\n`
      ).join('\n') +
      `\n## 4. แนวทางการบริหารความเสี่ยงและการยกเลิกแผน (Risk Management & Invalidation Rules)\n\n` +
      `- กำหนด Stop Loss ไม่เกิน 2-3% ของพอร์ตโฟลิโอต่อคำสั่งซื้อขาย\n` +
      `- หากราคาหลุดแนวรับสำคัญ หรือโครงสร้างตลาดเปลี่ยนเป็น Lower Low ให้ยกเลิกแผนทันที\n` +
      `- กระจายความเสี่ยงในสินทรัพย์หมวดหมู่หลัก (Core Assets) ควบคู่กับกลุ่ม High Growth\n\n` +
      `---\n` +
      `*จัดทำโดย: CryptoPro AI Decision Support Platform*\n`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `CryptoPro_Report_${selectedReportType}_${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', maxWidth: '1000px' }}>
      {/* Header & Report Actions */}
      <div className="card-header-row" style={{ marginBottom: '0' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <FileText size={22} color="var(--neon-cyan)" />
            <h2 style={{ fontSize: '20px', fontWeight: 800 }}>
              รายงานวิเคราะห์สภาวะตลาด (Market Intelligence Report)
            </h2>
          </div>
          <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginTop: '4px' }}>
            สรุปภาพรวมตลาดคริปโต โอกาสการลงทุน และการประเมินความเสี่ยงเชิงปริมาณอัจฉริยะ
          </p>
        </div>

        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
          <button onClick={handleDownloadReport} className="btn-secondary" style={{ fontSize: '12px', gap: '6px' }}>
            <Download size={14} color="var(--neon-green)" />
            <span>ดาวน์โหลด (.md)</span>
          </button>
          <button onClick={handleCopyReport} className="btn-secondary" style={{ fontSize: '12px', gap: '6px' }}>
            <Share2 size={14} />
            <span>{isCopied ? 'คัดลอกแล้ว!' : 'แชร์ / คัดลอก'}</span>
          </button>
          <button onClick={() => window.print()} className="btn-primary" style={{ fontSize: '12px', gap: '6px' }}>
            <Printer size={14} />
            <span>พิมพ์ / PDF</span>
          </button>
        </div>
      </div>


      {/* Report Type Selector */}
      <div style={{ display: 'flex', gap: '8px' }}>
        {[
          { id: 'daily', label: 'รายงานประจำวัน (Daily Briefing)' },
          { id: 'weekly', label: 'รายงานแนวโน้มรายสัปดาห์ (Weekly Macro)' },
          { id: 'risk', label: 'รายงานประเมินความเสี่ยง (Risk Assessment)' },
        ].map((type) => (
          <button
            key={type.id}
            onClick={() => setSelectedReportType(type.id as any)}
            style={{
              background: selectedReportType === type.id ? 'var(--neon-blue)' : 'var(--bg-card)',
              border: selectedReportType === type.id ? '1px solid #3B82F6' : '1px solid var(--border-color)',
              color: selectedReportType === type.id ? '#FFF' : 'var(--text-secondary)',
              padding: '6px 14px',
              borderRadius: '8px',
              fontSize: '12px',
              fontWeight: 600,
              cursor: 'pointer',
              transition: 'all 0.15s ease',
            }}
          >
            {type.label}
          </button>
        ))}
      </div>

      {/* Report Paper Container */}
      <div
        className="crypto-card"
        style={{
          padding: '28px',
          backgroundColor: '#0F172A',
          border: '1px solid rgba(59, 130, 246, 0.25)',
          display: 'flex',
          flexDirection: 'column',
          gap: '20px',
        }}
      >
        {/* Report Top Meta */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid rgba(255, 255, 255, 0.06)', paddingBottom: '16px' }}>
          <div>
            <div style={{ fontSize: '18px', fontWeight: 900, color: '#FFF', letterSpacing: '0.3px' }}>
              {currentMeta.title}
            </div>
            <div style={{ fontSize: '12px', color: 'var(--neon-cyan)', fontWeight: 700, marginTop: '2px' }}>
              {currentMeta.subtitle}
            </div>
          </div>

          <div style={{ textAlign: 'right', fontSize: '11.5px', color: 'var(--text-muted)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '4px', justifyContent: 'flex-end' }}>
              <Calendar size={13} />
              <span>{reportDate} • {reportTime}</span>
            </div>
            <div style={{ color: 'var(--neon-green)', marginTop: '2px', fontWeight: 600 }}>
              ● Live Multi-Exchange Sync ({currentMeta.badge})
            </div>
          </div>
        </div>

        {/* Section 1: Executive Market Summary */}
        <div>
          <h3 style={{ fontSize: '15px', fontWeight: 800, color: '#F1F5F9', marginBottom: '10px', display: 'flex', alignItems: 'center', gap: '6px' }}>
            <TrendingUp size={16} color="var(--neon-green)" />
            1. สรุปภาพรวมและสภาวะตลาด (Executive Summary)
          </h3>
          {selectedReportType === 'daily' && (
            <p style={{ fontSize: '13px', lineHeight: 1.6, color: '#CBD5E1' }}>
              ตลาดคริปโตเคอร์เรนซีในรอบ 24 ชั่วโมงที่ผ่านมาอยู่ในสภาวะ <strong>{kpis?.marketAITrend?.statusTh || 'สอดส่องและติดตาม'}</strong> โดยมีมูลค่าตลาดรวมอยู่ที่ <strong>{kpis?.totalMarketCapFormatted || '-'}</strong> (ปรับตัว {Number(kpis?.marketCapChange24h) >= 0 ? '+' : ''}{kpis?.marketCapChange24h || 0}%) พร้อมปริมาณการซื้อขายรวม <strong>{kpis?.volume24hFormatted || '-'}</strong> ดัชนีความกลัวและความโลภ (Fear &amp; Greed Index) อยู่ที่ระดับ <strong>{kpis?.fearAndGreedIndex || 0} ({kpis?.fearAndGreedSentiment || '-'})</strong> โมเมนตัมระยะสั้นยังคงกระจุกตัวในกลุ่มที่มีสัญญาณ AI บ่งชี้สะสมพลัง
            </p>
          )}
          {selectedReportType === 'weekly' && (
            <p style={{ fontSize: '13px', lineHeight: 1.6, color: '#CBD5E1' }}>
              ภาพรวมสภาวะตลาดรายสัปดาห์ (Weekly Macro) บ่งชี้การกระจายตัวของสภาพคล่องจาก Bitcoin สู่กลุ่ม Altcoins ชัดเจนขึ้น สัดส่วนการครองตลาดของ Bitcoin (BTC Dominance) อยู่ที่ <strong>{kpis?.btcDominance || 0}%</strong> ซึ่งเป็นจุดทดสอบการหมุนเวียนของเงินทุน (Capital Rotation) สู่หมวด <strong>Layer 1/Layer 2 และ DeFi</strong> ขณะที่ค่าเฉลี่ยสัปดาห์ของโมเมนตัม AI ยังคงเป็นบวกในสินทรัพย์หลัก
            </p>
          )}
          {selectedReportType === 'risk' && (
            <p style={{ fontSize: '13px', lineHeight: 1.6, color: '#CBD5E1' }}>
              การประเมินความเสี่ยงของตลาดโดยรวม (Risk Assessment) ตรวจพบค่าความผันผวนแฝง (Implied Volatility) อยู่ในเกณฑ์ปานกลาง ดัชนีความเสี่ยงพอร์ตโฟลิโอแนะระมัดระวังการเปิดสถานะแบบ Leverage สูงเนื่องจากมีโซน Liquidation Cluster หนาแน่นใกล้ระดับราคาแนวรับสำคัญ การกระจายสินทรัพย์ที่มีคะแนนความเสี่ยงต่ำ (Low Risk Profile) จะช่วยลดค่า Max Drawdown ได้อย่างมีนัยสำคัญ
            </p>
          )}
        </div>

        {/* Section 2: Macro Metrics Grid */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '10px' }}>
          <div style={{ backgroundColor: 'rgba(255, 255, 255, 0.03)', padding: '10px', borderRadius: '8px' }}>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>BTC Dominance</div>
            <div style={{ fontSize: '16px', fontWeight: 800, marginTop: '2px' }}>{kpis?.btcDominance}%</div>
            <div style={{ fontSize: '10.5px', color: 'var(--text-secondary)' }}>สัดส่วนการครองตลาด</div>
          </div>

          <div style={{ backgroundColor: 'rgba(255, 255, 255, 0.03)', padding: '10px', borderRadius: '8px' }}>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Bitcoin Price</div>
            <div style={{ fontSize: '16px', fontWeight: 800, marginTop: '2px' }}>
              {prefix}{kpis ? (kpis.btcPrice * multiplier).toLocaleString(undefined, { maximumFractionDigits: 0 }) : '-'}
            </div>
            <div style={{ fontSize: '10.5px', color: Number(kpis?.btcChange24h) >= 0 ? 'var(--neon-green-light)' : 'var(--neon-red)' }}>
              {Number(kpis?.btcChange24h) >= 0 ? '+' : ''}{kpis?.btcChange24h}% (24h)
            </div>
          </div>

          <div style={{ backgroundColor: 'rgba(255, 255, 255, 0.03)', padding: '10px', borderRadius: '8px' }}>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Ethereum Price</div>
            <div style={{ fontSize: '16px', fontWeight: 800, marginTop: '2px' }}>
              {prefix}{kpis ? (kpis.ethPrice * multiplier).toLocaleString(undefined, { maximumFractionDigits: 0 }) : '-'}
            </div>
            <div style={{ fontSize: '10.5px', color: Number(kpis?.ethChange24h) >= 0 ? 'var(--neon-green-light)' : 'var(--neon-red)' }}>
              {Number(kpis?.ethChange24h) >= 0 ? '+' : ''}{kpis?.ethChange24h}% (24h)
            </div>
          </div>

          <div style={{ backgroundColor: 'rgba(255, 255, 255, 0.03)', padding: '10px', borderRadius: '8px' }}>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Fear & Greed</div>
            <div style={{ fontSize: '16px', fontWeight: 800, color: 'var(--neon-cyan)', marginTop: '2px' }}>
              {kpis?.fearAndGreedIndex || 50}
            </div>
            <div style={{ fontSize: '10.5px', color: 'var(--text-secondary)' }}>{kpis?.fearAndGreedSentiment || 'Neutral'}</div>
          </div>
        </div>

        {/* Section 3: Dynamic Focused Opportunities */}
        <div>
          <h3 style={{ fontSize: '15px', fontWeight: 800, color: '#F1F5F9', marginBottom: '10px', display: 'flex', alignItems: 'center', gap: '6px' }}>
            <Sparkles size={16} color="var(--neon-cyan)" />
            {selectedReportType === 'risk'
              ? '2. สินทรัพย์ความเสี่ยงต่ำที่แนะนำสำหรับลดความผันผวน (Low Risk Defensive Assets)'
              : selectedReportType === 'weekly'
              ? '2. ผู้นำกระแสเงินทุนรอบสัปดาห์ (Weekly Capital Flow Leaders)'
              : '2. โอกาสการลงทุนที่โดดเด่นประจำวัน (Top AI Opportunities)'}
          </h3>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px' }}>
            {(selectedReportType === 'risk' && lowestRiskCoins.length > 0 ? lowestRiskCoins : topAI).map((coin, idx) => (
              <div
                key={coin.symbol}
                style={{
                  backgroundColor: 'rgba(255, 255, 255, 0.02)',
                  border: '1px solid rgba(59, 130, 246, 0.25)',
                  borderRadius: '10px',
                  padding: '12px',
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '6px' }}>
                  <span style={{ fontWeight: 800, fontSize: '15px' }}>{idx + 1}. {coin.symbol}</span>
                  <span className="badge badge-strong-buy">{coin.signalLabelTh}</span>
                </div>
                <div style={{ fontSize: '13px', fontWeight: 700, color: 'var(--neon-cyan)', marginBottom: '6px' }}>
                  AI Score: {coin.aiScore}/100 • ความเสี่ยง: {coin.riskLevel || 'medium'}
                </div>
                <p style={{ fontSize: '11.5px', color: 'var(--text-secondary)', lineHeight: 1.4 }}>
                  {coin.signalReasonTh}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Section 4: Risk & Invalidation Guidance */}
        <div style={{ backgroundColor: 'rgba(239, 68, 68, 0.06)', border: '1px solid rgba(239, 68, 68, 0.2)', borderRadius: '10px', padding: '14px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '13.5px', fontWeight: 800, color: '#EF4444', marginBottom: '6px' }}>
            <AlertTriangle size={16} />
            3. แนวทางการบริหารความเสี่ยงและการยกเลิกแผน ({selectedReportType === 'risk' ? 'Risk Defense Protocol' : 'Risk & Invalidation Rules'})
          </div>
          <ul style={{ paddingLeft: '20px', fontSize: '12px', color: '#E2E8F0', lineHeight: 1.6 }}>
            <li><strong>Position Sizing:</strong> ควบคุมความเสี่ยงไม่เกิน 1.5% - 2.0% ของพอร์ตรวมต่อหนึ่งไม้การลงทุน</li>
            <li><strong>Invalidation Trigger:</strong> หาก Bitcoin ปิดแท่ง 4H หลุดต่ำกว่าเส้น EMA 200 หรือเกิด Fake Breakout ให้ชะลอการเปิด Position ใหม่ในกลุ่ม Altcoins</li>
            <li><strong>Profit Taking:</strong> แบ่งไม้ขายทำกำไร (Partial TP) ที่อัตราส่วน Risk/Reward 1:2 และเลื่อนจุดตัดขาดทุนขึ้นมาที่หน้าทุน (Trailing Stop)</li>
          </ul>
        </div>

        {/* Footer Disclaimer */}
        <div style={{ borderTop: '1px solid rgba(255, 255, 255, 0.06)', paddingTop: '12px', fontSize: '11px', color: 'var(--text-muted)', textAlign: 'center' }}>
          เอกสารนี้จัดทำโดย CryptoPro AI Decision Support System เพื่อเป็นข้อมูลประกอบการตัดสินใจลงทุน ไม่ใช่คำชี้ชวนการลงทุน การลงทุนใน Cryptocurrency มีความเสี่ยงสูง ผู้ลงทุนควรศึกษาข้อมูลและบริหารความเสี่ยงอย่างรอบคอบ
        </div>
      </div>
    </div>
  );
};
