import { AgentDefinition } from '../types.js';

export const ALL_41_AGENTS: AgentDefinition[] = [
  // ==========================================================================
  // TEAM 1 — STOCK RANKING (10 Agents)
  // ==========================================================================
  {
    id: 'T1-01',
    name: 'Universe Screener Agent',
    thaiName: 'ผู้คัดกรองกรอบการลงทุน (Universe Screener)',
    team: 1,
    teamName: 'TEAM 1 — Stock Ranking',
    roleDescription: 'คัดกรองหุ้นเบื้องต้นจากหลักพันตัวตาม Market Cap, สภาพคล่อง, และปัจจัยพื้นฐานพื้นฐาน',
    specialty: 'Universe Filtering & Exchange Coverage',
    weight: 1.0,
    modelProvider: 'google',
    modelName: 'gemini-1.5-flash',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T1-02',
    name: 'Momentum Agent',
    thaiName: 'ผู้เชี่ยวชาญโมเมนตัมราคา (Momentum Analysis)',
    team: 1,
    teamName: 'TEAM 1 — Stock Ranking',
    roleDescription: 'คำนวณโมเมนตัม 1M, 3M, 6M, 12M, Relative Strength เทียบ S&P 500 / Nasdaq',
    specialty: 'Relative Strength & Trend Acceleration',
    weight: 1.0,
    modelProvider: 'google',
    modelName: 'gemini-1.5-flash',
    temperature: 0.2,
    isActive: true,
  },
  {
    id: 'T1-03',
    name: 'Technical Trend Agent',
    thaiName: 'ผู้ตรวจจับโครงสร้างแนวโน้มเทคนิค (Technical Trend)',
    team: 1,
    teamName: 'TEAM 1 — Stock Ranking',
    roleDescription: 'ประเมิน 50/200 EMA Golden Cross, Stage Analysis, Support/Resistance',
    specialty: 'Stage Analysis & Moving Average Clusters',
    weight: 0.9,
    modelProvider: 'google',
    modelName: 'gemini-1.5-flash',
    temperature: 0.2,
    isActive: true,
  },
  {
    id: 'T1-04',
    name: 'Quality Factor Agent',
    thaiName: 'ผู้ประเมินคุณภาพกิจการ (Quality Factor)',
    team: 1,
    teamName: 'TEAM 1 — Stock Ranking',
    roleDescription: 'คำนวณ ROE, ROIC, Gross Margin stability, D/E ratio, Piotroski F-Score',
    specialty: 'Capital Efficiency & Profitability Consistency',
    weight: 1.2,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T1-05',
    name: 'Growth Factor Agent',
    thaiName: 'ผู้ประเมินอัตราการเติบโต (Growth Factor)',
    team: 1,
    teamName: 'TEAM 1 — Stock Ranking',
    roleDescription: 'วิเคราะห์ Revenue CAGR, EPS Growth, Free Cash Flow Growth 3-5 ปีย้อนหลัง',
    specialty: 'Topline & Bottomline Expansion Acceleration',
    weight: 1.1,
    modelProvider: 'google',
    modelName: 'gemini-1.5-flash',
    temperature: 0.2,
    isActive: true,
  },
  {
    id: 'T1-06',
    name: 'Value Factor Agent',
    thaiName: 'ผู้ประเมินความคุ้มค่าราคา (Value Factor)',
    team: 1,
    teamName: 'TEAM 1 — Stock Ranking',
    roleDescription: 'เปรียบเทียบ P/E, Forward P/E, EV/EBITDA, P/FCF, PEG เทียบกับกลุ่มอุตสาหกรรม',
    specialty: 'Relative Valuation & Historical Multiples',
    weight: 0.9,
    modelProvider: 'google',
    modelName: 'gemini-1.5-flash',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T1-07',
    name: 'Earnings Revision Agent',
    thaiName: 'ผู้ติดตามการปรับคาดการณ์กำไร (Earnings Revision)',
    team: 1,
    teamName: 'TEAM 1 — Stock Ranking',
    roleDescription: 'ติดตาม Wall Street Consensus Upgrades/Downgrades และ EPS Surprise Rate',
    specialty: 'Consensus Drift & Revisions Momentum',
    weight: 1.1,
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.2,
    isActive: true,
  },
  {
    id: 'T1-08',
    name: 'Volume & Liquidity Agent',
    thaiName: 'ผู้ตรวจสอบสภาพคล่องและปริมาณซื้อขาย (Volume & Liquidity)',
    team: 1,
    teamName: 'TEAM 1 — Stock Ranking',
    roleDescription: 'วิเคราะห์ Average Daily Volume, Dollar Volume, Abnormal Volume Surge',
    specialty: 'Institutional Accumulation Volume & Bid-Ask Spread',
    weight: 0.8,
    modelProvider: 'google',
    modelName: 'gemini-1.5-flash',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T1-09',
    name: 'News & Catalyst Agent',
    thaiName: 'ผู้จับกระแสข่าวและปัจจัยเร่ง (News & Catalyst)',
    team: 1,
    teamName: 'TEAM 1 — Stock Ranking',
    roleDescription: 'สแกนข่าวประกาศเปิดตัวสินค้า, สัญญาภาครัฐ, งานแถลงข่าวนวัตกรรม, M&A',
    specialty: 'Immediate Event-Driven Catalysts',
    weight: 0.9,
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.3,
    isActive: true,
  },
  {
    id: 'T1-10',
    name: 'Ranking Chairman Agent',
    thaiName: 'ประธานคณะกรรมการจัดอันดับหุ้น (Ranking Chairman)',
    team: 1,
    teamName: 'TEAM 1 — Stock Ranking',
    roleDescription: 'รวบรวมคะแนนปัจจัยทั้งหมด ตัดสิน Top Candidates 10-20 ตัวส่งต่อให้ TEAM 2',
    specialty: 'Synthesis & Ranking Pipeline Governance',
    weight: 1.5,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },

  // ==========================================================================
  // TEAM 2 — EQUITY RESEARCH (10 Agents)
  // ==========================================================================
  {
    id: 'T2-01',
    name: 'Revenue / EPS / Growth Agent',
    thaiName: 'ผู้วิเคราะห์รายได้และกำไรต่อหุ้น (Revenue & EPS)',
    team: 2,
    teamName: 'TEAM 2 — Equity Research',
    roleDescription: 'เจาะลึกที่มาของรายได้แต่ละ Product Line, Gross Margin และ Net Margin expansion',
    specialty: 'Revenue Decomposition & Unit Economics',
    weight: 1.1,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T2-02',
    name: 'Income Statement Agent',
    thaiName: 'ผู้วิเคราะห์งบกำไรขาดทุน (Income Statement)',
    team: 2,
    teamName: 'TEAM 2 — Equity Research',
    roleDescription: 'ตรวจทาน Operating Leverage, SG&A to Revenue, R&D intensity',
    specialty: 'P&L Line-by-Line Integrity',
    weight: 1.0,
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T2-03',
    name: 'Balance Sheet Agent',
    thaiName: 'ผู้วิเคราะห์งบดุลและความแข็งแกร่งทางการเงิน (Balance Sheet)',
    team: 2,
    teamName: 'TEAM 2 — Equity Research',
    roleDescription: 'ประเมินภาระหนี้ Net Debt / EBITDA, Quick Ratio, Debt Maturity Schedule',
    specialty: 'Solvency, Capital Structure & Debt Profiling',
    weight: 1.1,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T2-04',
    name: 'Cash Flow / FCF Agent',
    thaiName: 'ผู้วิเคราะห์กระแสเงินสดอิสระ (Cash Flow / FCF)',
    team: 2,
    teamName: 'TEAM 2 — Equity Research',
    roleDescription: 'วัด Free Cash Flow Conversion, CapEx reinvestment efficiency, Buyback power',
    specialty: 'Operating Cash Flow Quality & Capex Efficiency',
    weight: 1.2,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T2-05',
    name: 'Valuation Agent',
    thaiName: 'ผู้ประเมินมูลค่าแท้จริง (Intrinsic Valuation)',
    team: 2,
    teamName: 'TEAM 2 — Equity Research',
    roleDescription: 'สร้างโมเดล DCF 2-stage, Reverse DCF, Fair Value Bull/Base/Bear scenarios',
    specialty: 'DCF Modelling & Fair Value Bands',
    weight: 1.3,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T2-06',
    name: 'Business / Moat Agent',
    thaiName: 'ผู้วิเคราะห์ความได้เปรียบเชิงแข่งขันและคูเมือง (Economic Moat)',
    team: 2,
    teamName: 'TEAM 2 — Equity Research',
    roleDescription: 'วิเคราะห์ Network Effects, Switching Costs, Cost Advantages, Intangible Assets',
    specialty: 'Competitive Moat Durability',
    weight: 1.1,
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.2,
    isActive: true,
  },
  {
    id: 'T2-07',
    name: 'Management Agent',
    thaiName: 'ผู้ประเมินคณะผู้บริหารและบรรษัทภิบาล (Management & Governance)',
    team: 2,
    teamName: 'TEAM 2 — Equity Research',
    roleDescription: 'ตรวจสอบ Track Record ของ CEO/CFO, Capital Allocation Discipline, Insider Ownership',
    specialty: 'Capital Allocation & Executive Alignment',
    weight: 1.0,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T2-08',
    name: 'Earnings Call / Guidance Agent',
    thaiName: 'ผู้วิเคราะห์การแถลงผลประกอบการ (Earnings Call & Guidance)',
    team: 2,
    teamName: 'TEAM 2 — Equity Research',
    roleDescription: 'ถอดรหัส Tone จาก Earnings Transcript, Management Tone Shift, Forward Guidance',
    specialty: 'Transcript Sentiment & Guidance Revisions',
    weight: 1.0,
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.2,
    isActive: true,
  },
  {
    id: 'T2-09',
    name: 'Industry / Competitor Agent',
    thaiName: 'ผู้วิเคราะห์โครงสร้างอุตสาหกรรมและคู่แข่ง (Industry Landscape)',
    team: 2,
    teamName: 'TEAM 2 — Equity Research',
    roleDescription: 'วิเคราะห์ TAM (Total Addressable Market), Market Share Shifts, Porter 5 Forces',
    specialty: 'Sector Structure & Competitive Dynamics',
    weight: 1.0,
    modelProvider: 'google',
    modelName: 'gemini-1.5-pro',
    temperature: 0.2,
    isActive: true,
  },
  {
    id: 'T2-10',
    name: 'Research Chairman Agent',
    thaiName: 'ประธานคณะกรรมการวิจัยหุ้น (Research Chairman)',
    team: 2,
    teamName: 'TEAM 2 — Equity Research',
    roleDescription: 'รวบรวมและสังเคราะห์ Research Thesis ทั้ง Bull, Base, Bear และ Fair Value สรุปส่งต่อ TEAM 3',
    specialty: 'Comprehensive Equity Thesis Synthesis',
    weight: 1.5,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },

  // ==========================================================================
  // TEAM 3 — RED TEAM ANALYSIS (10 Agents)
  // ==========================================================================
  {
    id: 'T3-01',
    name: 'Bear Case Agent',
    thaiName: 'ผู้วิเคราะห์สมมติฐานขาลงสุดโต่ง (Worst-Case Bear Thesis)',
    team: 3,
    teamName: 'TEAM 3 — Red Team Analysis',
    roleDescription: 'สร้างสมมติฐานที่แย่ที่สุด หาจุดเปราะบางที่จะทำให้กำไรและมูลค่าตกฮวบ',
    specialty: 'Downside Stress-Testing & Thesis Destruction',
    weight: 1.2,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.2,
    isActive: true,
  },
  {
    id: 'T3-02',
    name: 'Accounting / Forensic Agent',
    thaiName: 'ผู้ตรวจสอบนิติวิทยาทางบัญชี (Forensic Accounting)',
    team: 3,
    teamName: 'TEAM 3 — Red Team Analysis',
    roleDescription: 'ตรวจจับสัญญาณผิดปกติ Beneish M-Score, DSO พุ่ง, การบันทึกรายได้ก่อนเวลา, Goodwill Bloat',
    specialty: 'Earnings Quality & Financial Red Flags',
    weight: 1.4,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T3-03',
    name: 'Valuation Challenge Agent',
    thaiName: 'ผู้คัดค้านความสมเหตุสมผลของราคา (Valuation Challenge)',
    team: 3,
    teamName: 'TEAM 3 — Red Team Analysis',
    roleDescription: 'โต้แย้งสมมติฐาน Terminal Growth Rate, WACC ที่ต่ำเกินไป และ Multiple ที่แพงเกินจริง',
    specialty: 'Multiple Compression & Overvaluation Risk',
    weight: 1.1,
    modelProvider: 'google',
    modelName: 'gemini-1.5-pro',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T3-04',
    name: 'Earnings Risk Agent',
    thaiName: 'ผู้ประเมินความเสี่ยงงบการเงินสะดุด (Earnings Miss Risk)',
    team: 3,
    teamName: 'TEAM 3 — Red Team Analysis',
    roleDescription: 'ประเมินความเสี่ยงที่จะ Miss Estimates ในไตรมาสถัดไปจาก Supply Chain, ต้นทุน หรือ FX',
    specialty: 'Short-term Guidance Vulnerabilities',
    weight: 1.0,
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.2,
    isActive: true,
  },
  {
    id: 'T3-05',
    name: 'Technical Breakdown Agent',
    thaiName: 'ผู้ตรวจจับโครงสร้างเทคนิคพังทลาย (Technical Breakdown)',
    team: 3,
    teamName: 'TEAM 3 — Red Team Analysis',
    roleDescription: 'ตรวจจับ Bearish Divergence, Head & Shoulders, Loss of Key Moving Averages',
    specialty: 'Distribution Patterns & Support Violations',
    weight: 1.0,
    modelProvider: 'google',
    modelName: 'gemini-1.5-flash',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T3-06',
    name: 'Macro Risk Agent',
    thaiName: 'ผู้ประเมินความเสี่ยงมหภาค (Macroeconomic Headwinds)',
    team: 3,
    teamName: 'TEAM 3 — Red Team Analysis',
    roleDescription: 'ประเมินผลกระทบจากดอกเบี้ยสูง, เงินเฟ้อ, ความเสี่ยง Geopolitical, นโยบายกำแพงภาษี',
    specialty: 'Interest Rate Sensitivity & Geopolitical Risks',
    weight: 1.1,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T3-07',
    name: 'Industry Risk Agent',
    thaiName: 'ผู้ประเมินความเสี่ยงคู่แข่งและการแทนที่ (Industry Disruption)',
    team: 3,
    teamName: 'TEAM 3 — Red Team Analysis',
    roleDescription: 'ตรวจสอบ Big Tech เข้ามาแย่งตลาด, AI Disruption, กฎหมายกำกับดูแลใหม่ (Antitrust)',
    specialty: 'Technological Substitution & Regulatory Clamps',
    weight: 1.0,
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.2,
    isActive: true,
  },
  {
    id: 'T3-08',
    name: 'Crowded Trade / Sentiment Agent',
    thaiName: 'ผู้ตรวจจับภาวะความหนาแน่นของการเก็งกำไร (Crowded Trade Risk)',
    team: 3,
    teamName: 'TEAM 3 — Red Team Analysis',
    roleDescription: 'ตรวจสอบ Short Interest, Institutional Over-ownership, Retail Euphoria sentiment',
    specialty: 'Excessive Positioning & Long Squeeze Exposure',
    weight: 1.0,
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.2,
    isActive: true,
  },
  {
    id: 'T3-09',
    name: 'Portfolio Correlation Agent',
    thaiName: 'ผู้ตรวจวัดความเสี่ยงการกระจุกตัวในพอร์ต (Portfolio Correlation Risk)',
    team: 3,
    teamName: 'TEAM 3 — Red Team Analysis',
    roleDescription: 'คำนวณ Correlation กับหุ้นเดิมในพอร์ต หากสูงเกินไปจะคัดค้านเพื่อกันความเสี่ยงกระจุก',
    specialty: 'Covariance & Sector Overlap Defense',
    weight: 1.1,
    modelProvider: 'google',
    modelName: 'gemini-1.5-flash',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T3-10',
    name: 'Red Team Chairman Agent',
    thaiName: 'ประธานทีมเรดทีมผู้มีสิทธิ์ Veto (Red Team Chairman & Veto Master)',
    team: 3,
    teamName: 'TEAM 3 — Red Team Analysis',
    roleDescription: 'สรุป Red Team Score และตัดสินใจขั้นเด็ดขาดว่าจะออกสิทธิ์ RED_TEAM_VETO หรือไม่',
    specialty: 'Absolute Risk Challenge & Veto Enforcement',
    weight: 1.5,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },

  // ==========================================================================
  // TEAM 4 — TACTICAL ASSET ALLOCATION (10 Agents)
  // ==========================================================================
  {
    id: 'T4-01',
    name: 'Market Regime Agent',
    thaiName: 'ผู้กำหนดสภาวะตลาดรวม (Market Regime Identification)',
    team: 4,
    teamName: 'TEAM 4 — Tactical Asset Allocation',
    roleDescription: 'วิเคราะห์ VIX, Yield Curve, Breadth เพื่อกำหนด Risk-On / Risk-Off Regime',
    specialty: 'Macro Regime & Volatility Environment',
    weight: 1.3,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T4-02',
    name: 'Sector Allocation Agent',
    thaiName: 'ผู้บริหารสัดส่วนกลุ่มอุตสาหกรรม (Sector Rotation)',
    team: 4,
    teamName: 'TEAM 4 — Tactical Asset Allocation',
    roleDescription: 'ควบคุมไม่ให้พอร์ต Overweight กลุ่มอุตสาหกรรมใดกลุ่มหนึ่งเกินเกณฑ์',
    specialty: 'Sector Weight Limits & Rotation Flow',
    weight: 1.1,
    modelProvider: 'google',
    modelName: 'gemini-1.5-flash',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T4-03',
    name: 'Portfolio Construction Agent',
    thaiName: 'ผู้ออกแบบโครงสร้างพอร์ตโฟลิโอ (Portfolio Construction)',
    team: 4,
    teamName: 'TEAM 4 — Tactical Asset Allocation',
    roleDescription: 'คำนวณการกระจายความเสี่ยง Efficient Frontier, Max Sharpe, Target Volatility',
    specialty: 'Mean-Variance & Risk Parity Weights',
    weight: 1.2,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T4-04',
    name: 'Position Sizing Agent',
    thaiName: 'ผู้คำนวณขนาดไม้ลงทุนตามความเสี่ยง (Position Sizing & Kelly)',
    team: 4,
    teamName: 'TEAM 4 — Tactical Asset Allocation',
    roleDescription: 'ใช้ Fractional Kelly Criterion ร่วมกับ Fixed Fractional Risk เพื่อกำหนด Position Size',
    specialty: 'Kelly Optimization & Capital Preservation',
    weight: 1.3,
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T4-05',
    name: 'Entry Timing Agent',
    thaiName: 'ผู้กำหนดจังหวะและโซนเข้าซื้อ (Entry Timing & Limits)',
    team: 4,
    teamName: 'TEAM 4 — Tactical Asset Allocation',
    roleDescription: 'กำหนด Entry Zone ไม่ไล่ราคา รอ Pullback ไปยัง Demand Zone หรือ Key Moving Average',
    specialty: 'Price Action & Pullback Confirmation',
    weight: 1.1,
    modelProvider: 'google',
    modelName: 'gemini-1.5-flash',
    temperature: 0.2,
    isActive: true,
  },
  {
    id: 'T4-06',
    name: 'Stop / Invalidation Agent',
    thaiName: 'ผู้กำหนดจุดตัดขาดทุนและจุดเสียทรง (Stop Loss & Invalidation)',
    team: 4,
    teamName: 'TEAM 4 — Tactical Asset Allocation',
    roleDescription: 'คำนวณจุด Invalidation จาก ATR, Market Structure Low, Breakout Failure Level',
    specialty: 'ATR Volatility Stops & Thesis Invalidation',
    weight: 1.3,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T4-07',
    name: 'Profit Target Agent',
    thaiName: 'ผู้กำหนดเป้าหมายทำกำไรหลายระดับ (Multi-Tier Take Profit)',
    team: 4,
    teamName: 'TEAM 4 — Tactical Asset Allocation',
    roleDescription: 'คำนวณ TP1, TP2, TP3 อิงตาม Fib Expansion, Resistance Zones, และ Fair Value',
    specialty: 'Risk-Reward Optimization & Scaling Out',
    weight: 1.1,
    modelProvider: 'google',
    modelName: 'gemini-1.5-flash',
    temperature: 0.2,
    isActive: true,
  },
  {
    id: 'T4-08',
    name: 'Hedging Agent',
    thaiName: 'ผู้เสนอมาตรการป้องกันความเสี่ยง (Portfolio Hedging)',
    team: 4,
    teamName: 'TEAM 4 — Tactical Asset Allocation',
    roleDescription: 'เสนอการถือเงินสดสำรอง หรือการใช้ Index Inverse ETF / Protective Puts เมื่อจำเป็น',
    specialty: 'Tail-Risk Protection & Cash Buffer Strategy',
    weight: 1.0,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T4-09',
    name: 'Execution / Slippage Agent',
    thaiName: 'ผู้ประเมินการส่งคำสั่งและการลื่นไถลของราคา (Execution & Slippage)',
    team: 4,
    teamName: 'TEAM 4 — Tactical Asset Allocation',
    roleDescription: 'จำลองผลกระทบต่อราคาตลาด (Market Impact), TWAP/VWAP และประเมินค่า Slippage',
    specialty: 'Order Routing & Microstructure Impact',
    weight: 0.9,
    modelProvider: 'google',
    modelName: 'gemini-1.5-flash',
    temperature: 0.1,
    isActive: true,
  },
  {
    id: 'T4-10',
    name: 'Portfolio Chairman Agent',
    thaiName: 'ประธานคณะกรรมการจัดสรรพอร์ตโฟลิโอ (Portfolio Chairman)',
    team: 4,
    teamName: 'TEAM 4 — Tactical Asset Allocation',
    roleDescription: 'รวมข้อเสนอของ TEAM 4 ทั้งหมด สร้าง Trade Plan ฉบับสมบูรณ์เสนอต่อ AI-CIO',
    specialty: 'Comprehensive Trade Plan Formulation',
    weight: 1.5,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },

  // ==========================================================================
  // AI-CIO — CHIEF INVESTMENT OFFICER (1 Agent)
  // ==========================================================================
  {
    id: 'AI-CIO',
    name: 'Chief Investment Officer (AI-CIO)',
    thaiName: 'ประธานเจ้าหน้าที่บริหารการลงทุน (AI-CIO)',
    team: 'CIO',
    teamName: 'INVESTMENT COMMITTEE SUPREME COUNCIL',
    roleDescription: 'ผู้นำสูงสุดของ Investment Committee รวบรวมผลทั้ง 4 ทีม ตัดสินใจขั้นสุดท้ายก่อนส่งเข้า Risk Engine',
    specialty: 'Final Investment Decision & Thesis Governance',
    weight: 2.0,
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.1,
    isActive: true,
  },
];

export function getAgentsByTeam(team: 1 | 2 | 3 | 4 | 'CIO'): AgentDefinition[] {
  return ALL_41_AGENTS.filter((a) => a.team === team);
}

export function getAgentById(id: string): AgentDefinition | undefined {
  return ALL_41_AGENTS.find((a) => a.id === id);
}
